name: dispatch
channels:
  - conda-forge
dependencies:
  # Packages required for setting up the environment
  - pip>=21.0,<23
  - python>=3.10,<3.12

  # Use pip to install the package defined by this repo for development:
  - pip:
      - --editable ./[dev,doc,tests,viz]
