name: cheshire
channels:
  - conda-forge
  - defaults
dependencies:
  # Packages required for setting up the environment
  - pip>=21,<23
  - python>=3.8,<3.11
  - setuptools<62

  # Packages specified in setup.py that need or benefit from binary conda packages
  # - geopandas>=0.9,<0.11
  # - pygeos>=0.10,<0.13  # Python wrappers for the GEOS spatial libraries
  # - python-snappy>=0.6,<0.7  # Supports snappy compression in pyarrow/parquet

  # Packages not specified in setup.py that provide optional, helpful binaries:
  # - numba>=0.55.1,<0.56  # numba speeds up some kinds of math by 100x

  # Jupyter packages:
  - jupyterlab>=3.2,<4
  - nbconvert>=6,<7 # Used to clear notebook outputs in pre-commit hooks

  # Use pip to install the package defined by this repo for development:
  - pip:
      - --editable ./[dev,docs,tests,types]
