name: dispatch
channels:
  - conda-forge
dependencies:
  # Packages required for setting up the environment
  - pip>=21.0,<23
  - python>=3.10,<3.11
  - bottleneck~=1.3
  - numba >= 0.55.1,<0.57
  - numexpr ~= 2.8
  - numpy >= 1.18.5,<2
  - pandas >= 1.4,<1.5
  - pyarrow >= 7,<10

  # Use pip to install the package defined by this repo for development:
  - pip:
      - --editable ./[dev,docs,tests,types]
