name: dispatch
channels:
  - conda-forge
dependencies:
  # Packages required for setting up the environment
  - pip>=21.0,<23
  - python>=3.10,<3.11
  - bottleneck >= 1.3,<1.3.6
  - numba >= 0.55.1,<0.57
  - numexpr >= 2.8, <2.8.5
  - numpy >= 1.18.5,<2
  - pandas >= 1.4,<1.6
  - pandera >= 0.12
  - pyarrow >= 7,<11
  - plotly>5.10,<=5.11

  # Use pip to install the package defined by this repo for development:
  - pip:
      - --editable ./[dev,doc,tests,viz]
