[build-system]
requires = ["setuptools<64", "setuptools_scm"]

[tool.setuptools_scm]

[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310"]
include = "\\.pyi?$"

[tool.isort]
profile = "black"
known_first_party = ["dispatch"]

[tool.bandit]
exclude_dirs = ["tests"]
tests = ["B201", "B301"]
skips = ["B101", "B601"]
