"""Constants."""
from __future__ import annotations

import pandas as pd

MTDF = pd.DataFrame()
COLOR_MAP = {
    "Gas CC": "#c85c19",
    "Gas CT": "#f58228",
    "Gas RICE": "#fbbb7d",
    "Gas ST": "#ffdaab",
    "Coal": "#5f2803",
    "Coal CCS": "#a68462",
    "Hydro": "#007b7b",
    "Nuclear": "#3e3969",
    "Other Fossil": "#7d492c",
    "Biomass": "#556940",
    "Solar": "#ffcb05",
    "Onshore Wind": "#005d7f",
    "Offshore Wind": "#529cba",
    "Storage": "#7b76ad",
    "Charge": "#7b76ad",
    "Discharge": "#7b76ad",
    "Curtailment": "#dae4c1",
    "Deficit": "#df897b",
    "Net Load": "#58585b",
    "Grossed Load": "#58585b",
    "Gross Load": "#58585b",
}
PLOT_MAP = {
    "Conventional Hydroelectric": "Hydro",
    "Nuclear": "Nuclear",
    "Petroleum Liquids": "Other Fossil",
    "Natural Gas Steam Turbine": "Gas ST",
    "Conventional Steam Coal": "Coal",
    "Natural Gas Fired Combined Cycle": "Gas CC",
    "Natural Gas Fired Combustion Turbine": "Gas CT",
    "Natural Gas Internal Combustion Engine": "Gas RICE",
    "Coal Integrated Gasification Combined Cycle": "Coal",
    "Steam Coal w/ CCS": "Coal CCS",
    "Other Gases": "Other Fossil",
    "Petroleum Coke": "Other Fossil",
    "Wood/Wood Waste Biomass": "Biomass",
    "Other Waste Biomass": "Biomass",
    "Landfill Gas": "Biomass",
    "Municipal Solid Waste": "Biomass",
    "All Other": "Other Fossil",
    "solar": "Solar",
    "Solar Photovoltaic": "Solar",
    "onshore_wind": "Onshore Wind",
    "offshore_wind": "Offshore Wind",
    "Onshore Wind Turbine": "Onshore Wind",
    "Offshore Wind Turbine": "Offshore Wind",
    "curtailment": "Curtailment",
    "deficit": "Deficit",
    # "charge": "Storage",
    # "discharge": "Storage",
    "Batteries": "Storage",
    "H2 Storage": "Storage",
}
ORDERING = {
    "nuclear": "000",
    "coal": "001",
    "coal ccs": "0015",
    "gas cc": "002",
    "gas ct": "004",
    "gas rice": "005",
    "gas st": "003",
    "other fossil": "006",
    "hydro": "007",
    "biomass": "008",
    "solar": "011",
    "onshore wind": "009",
    "offshore wind": "010",
    "storage": "012",
    "curtailment": "013",
    "january": "101",
    "february": "102",
    "march": "103",
    "april": "104",
    "may": "105",
    "june": "106",
    "july": "107",
    "august": "108",
    "september": "109",
    "october": "110",
    "november": "111",
    "december": "112",
    "historical": "200",
    "redispatch": "201",
}
