---
name: bot-auto-merge

on:
  workflow_run:
    types: [completed]
    workflows: ["tox-pytest"]

jobs:
  #  automerge:
  #    runs-on: ubuntu-latest
  #
  #    permissions:
  #      pull-requests: write
  #      contents: write
  #
  #    steps:
  #      - uses: fastify/github-action-merge-dependabot@v3.3.0

  bot_auto_merge:
    runs-on: ubuntu-latest

    #    permissions:
    #      pull-requests: write
    #      contents: write
    # finally working https://github.com/ridedott/merge-me-action/issues/1581
    steps:
      - name: Impersonate update bot
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_KEY }}
      - name: Auto-merge passing dependabot PRs
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2
        with:
          # For clarity only. dependabot is default.
          GITHUB_LOGIN: dependabot
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          ENABLED_FOR_MANUAL_CHANGES: "true"
      - name: Auto-merge passing pre-commit-ci PRs
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_LOGIN: pre-commit-ci
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          ENABLED_FOR_MANUAL_CHANGES: "true"
